version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: sudo pip install -U pytest
      - run: pytest
  mypy:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: sudo pip3 install -U mypy
      - run: mypy -p capstone360
