version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: echo "this doesn't do anything yet!"
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: sudo pip install -U pytest
      - run: pytest
  mypy:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: sudo pip3 install -U mypy
      - run: mypy -p capstone360
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - mypy
