version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: pip install --user -U pytest
      - run: pytest
  mypy:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: pip3 install --user -U mypy
      - run: mypy -p capstone360
