version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Get build dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install -y build-essential debhelper devscripts equivs dh-virtualenv
            apt-get install -y libpython3.5 python3-dev python3-setuptools python3-pip
      - checkout
      - run: dpkg-buildpackage -us -uc
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: sudo pip install -U pytest
      - run: sudo pip install -r requirements.txt
      - run: python3 -m pytest tests/
  mypy:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: sudo pip3 install -U mypy
      - run: mypy -p capstone360
  lint:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: sudo pip3 install -U flake8
      - run: flake8 --max-line-length=110

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - lint
      - build
      # - mypy
